### PR TITLE
Pg spanner misc fixes

### LINKED ISSUE #241: TargetDB handling in getDDL() calls
func (s Schema) GetDDL(c Config) takes a config that accepts targetDB in the struct which is left out in a few places like the WriteSchemaFile() causing the generated schema files to be of GOOGLESQL dialect when specified dialect is PG.

ALso, FK statements still use backticks `` instead of "" for PG spanner. Check if any other handling is required.

### PR DESCRIPTION
**Pull request by Deep1998**
Fixes #241, #244 and #245 

- Added handling for float and null values
- For pg dump, null values were not getting skipped earlier.
- Quoting was incorrect for pg dialect, causing foreign key statements to fail
- The schema files were of spanner dialect since targetdb was not passed as a param.

### CODE REVIEW

File: sources/postgres/pgdump.go [hunk 1]
```diff
@@ -732,6 +732,12 @@ func getRows(conv *internal.Conv, vll []*pg_query.Node, n *pg_query.InsertStmt)
 						// high priority (it isn't right now), then consider preserving int64
 						// here to avoid the int64 -> string -> int64 conversions.
 						values = append(values, strconv.FormatInt(int64(c.Integer.Ival), 10))
+					case *pg_query.Node_Float:
+						values = append(values, c.Float.Str)
+					case *pg_query.Node_Null:
```
Comment (Deep1998) [inline sources/postgres/pgdump.go:737]: For rows of the form (NULL, 14.67), the pg_query node type is Node_Null and Node_Float respectively. 

Data dumped with quotes ('NULL', '14.67') would have worked as it would get classified as Node_String_ but without quotes, the pg_query parser assigns a different type to the data.

File: spanner/ddl/ast.go [hunk 2]
```diff
@@ -158,7 +158,11 @@ type Config struct {
 
 func (c Config) quote(s string) string {
 	if c.ProtectIds {
-		return "`" + s + "`"
+		if c.TargetDb == constants.TargetExperimentalPostgres {
+			return "\"" + s + "\""
```
Comment (Deep1998) [inline spanner/ddl/ast.go:162]: PG dialect uses " instead of `

File: sources/postgres/data.go [hunk 3]
```diff
@@ -76,7 +76,10 @@ func ConvertData(conv *internal.Conv, srcTable string, srcCols []string, vals []
 	}
 	for i, spCol := range spCols {
 		srcCol := srcCols[i]
-		if vals[i] == "\\N" { // PostgreSQL representation of empty column in COPY-FROM blocks.
+		// "\\N" is for PostgreSQL representation of empty column in COPY-FROM blocks.
+		// TODO: Consider using NullString to differentiate between an actual column having "NULL" as a string
```
Comment (Deep1998) [inline sources/postgres/data.go:80]: Kept this as a todo because we currently skip if vals[i] == "NULL" across all engines.

File: sources/postgres/pgdump.go (hunk 1 above)
Comment (bharadwaj-aditya) [reply sources/postgres/pgdump.go:737]: what is the different type that gets assigned ? Add this description in comments within the code

File: spanner/ddl/ast_test.go [hunk 4]
```diff
@@ -88,7 +88,7 @@ func TestPrintColumnDefPG(t *testing.T) {
 		{in: ColumnDef{Name: "col1", T: Type{Name: Int64, IsArray: true}}, expected: "col1 VARCHAR(2621440)"},
 		{in: ColumnDef{Name: "col1", T: Type{Name: Int64}, NotNull: true}, expected: "col1 INT8 NOT NULL"},
 		{in: ColumnDef{Name: "col1", T: Type{Name: Int64, IsArray: true}, NotNull: true}, expected: "col1 VARCHAR(2621440) NOT NULL"},
-		{in: ColumnDef{Name: "col1", T: Type{Name: Int64}}, protectIds: true, expected: "`col1` INT8"},
+		{in: ColumnDef{Name: "col1", T: Type{Name: Int64}}, protectIds: true, expected: "\"col1\" INT8"},
```
Comment (bharadwaj-aditya) [inline spanner/ddl/ast_test.go:91]: how were the backticks working earlier ?

**Review by bharadwaj-aditya — CHANGES_REQUESTED** [review]

File: spanner/ddl/ast_test.go (hunk 4 above)
Comment (Deep1998) [reply spanner/ddl/ast_test.go:91]: Because the quote() function did not have handling for PG. It always defaulted to backticks. This Pr added the changes in quote() above that if dialect is pg, use double quotes.

File: sources/postgres/pgdump.go (hunk 1 above)
Comment (Deep1998) [reply sources/postgres/pgdump.go:740]: Done

**Review by bharadwaj-aditya — APPROVED** [review]
LGTM
